### ISSUE TITLE
Reset password dialog - no error on invalid password

### ISSUE THREAD

**Issue by heinzc** [vicinityh2020/vicinity-neighbourhood-manager#11]
**Describe the bug**
When resetting the password (via link in email), I can change my password and get the confirmation it was changed successfully. However if the new password was invalid (e.g. has less than 8 characters), I cannot log in with this new password. Even though the notification claims everything went ok

**To Reproduce**
1. Forget Password
2. On login screen, click on "Forgot my Password"
3. Enter email, confirm and wait for email to arrive
4. using the link from the email, try to reset the password to something short, e.g. "123"

**Expected behavior**
Either password should be changed or error message should appear telling that the new password is invalid

**Actual behavior**
UI tells "password changed successfully", yet login with the new password is not possible

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari, should be similar in all browsers

**Comment by Joralmi** [comment]
Issue resolved in current neighbourhood_manager_ui repository.
github.com:vicinityh2020/neighbourhood_manager_ui.git
